name: Build Workflow
on: workflow_dispatch
  # push:
  #   branches: [ main ]
permissions:
  contents: write        # allows creating dispatch events
  actions: write         # allows triggering other workflows

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run build
        run: echo "Building project..."

      - name: Trigger Deploy Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-deploy
          client-payload: '{"environment":"staging"}'
